services:
  link_shortener:
    build:
      context: ./internal/link
      dockerfile: app.Dockerfile
    ports:
      - "8081:80"

  postgres:
    image: "postgres:15.4"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      TZ: Asia/Tehran
    volumes:
        - postgresql:/data/postgres
        - ./docker/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  minio:
    image: "minio/minio:latest"
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./minio/data:/data

volumes:
  postgresql: