openapi: "3.0.0"
info:
  title: Link Shortener
  description: Link Shortener
  version: 1.0.0
servers:
  - url: "https://{hostname}/api"
    variables:
      hostname:
        default: localhost
  - url: "http://{hostname}/api"
    variables:
      hostname:
        default: localhost
security:
  - bearerAuth: [ ]
paths:
  /links:
    post:
      operationId: createLink
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLink'
      responses:
        '201':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
  /links/{shortLink}:
    get:
      operationId: redirectLink
      parameters:
        - in: path
          name: shortLink
          schema:
            type: string
          required: true
          description: todo
      responses:
        '308':
          description: redirect to original url

components:
  schemas:
    Link:
      type: object
      required: [ original_link, short_link ]
      properties:
        original_link:
          type: string
        short_link:
          type: string
    CreateLink:
      type: object
      required: [ original_link ]
      properties:
        original_link:
          type: string
